<Project>
  <PropertyGroup>
    <!-- Centralize publish settings to help CI change them in one place -->
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>link</TrimMode>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <Version>1.0.0</Version>
  </PropertyGroup>
</Project>
